name: CI

on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install dependencies with npm
        run: npm install && npm install -g @lhci/cli@0.4.x

      - name: Build site
        run: npm run build

      - name: Run Lighthouse CI
        run: lhci autorun --upload.target=temporary-public-storage
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
