name: Daily Netlify Build

on:
  schedule:
    # Run at 0400 daily (AZ time)
    - cron: '0 11 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Trigger build
        uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
